CREATE DATABASE IF NOT EXISTS registrationDB;

USE registrationDB;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  mobile VARCHAR(15) UNIQUE,
  password VARCHAR(255)
);
